apiVersion: v1
kind: Pod
metadata:
  name: app-ass2
  labels:
    name: app-ass2
spec:
  containers:
    - name: app-ass2
      image: 838856494475.dkr.ecr.us-east-1.amazonaws.com/ass1_application:v0.1
      ports:
        - containerPort: 8080
      env:
      - name: DBHOST
        value: dbservice.sqldb.svc.cluster.local
      - name: DBUSER
        value: root
      - name: DBPORT
        value: "3306"
      - name: APP_COLOR
        value: blue
      - name: DBPWD
        value: ish