apiVersion: v1
kind: Service
metadata:
  name: appservice
  labels:
    name: app-ass2
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    name: app-ass2