apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: db-rep
 labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: db-rep
          image: 838856494475.dkr.ecr.us-east-1.amazonaws.com/ass1_database:v0.1
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ish